simple_model:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

  base_to_second_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 1.0, i: 1.0, d: 0.0}

  base_to_third_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 100.0, i: 0, d: 0.0}

  third_to_fourth_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 100.0, i: 0, d: 0.0}

  second_to_fifth_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint4
    pid: {p: 100.0, i: 0, d: 0.0}
